### ISSUE TITLE
Add `secret_token` field to S3

### ISSUE THREAD

**Issue by josevalim** [elixir-explorer/fss#5]
Livebook v0.12 may now set this field. We need to:

1. Add this field to S3 here
2. Pass down this field in Explorer
3. Receive this field from Livebook in Kino

**Comment by philss** [comment]
@josevalim we have a `token` field that represents the `session_token`. Is this the same thing? I mean, is it `secret_token` or `session_token`? And if it's the same, should we rename the `token` field to `session_token`?

**Comment by josevalim** [comment]
Perfect, they are the same and we chose to rename it from session_token to token in Livebook. :) So this is done! Thank you!
